### ISSUE TITLE
Support pnpm workspaces 

### ISSUE THREAD

**Issue by creepinson** [mikkotikkanen/supermon#51]
I am using a monorepo (w/ pnpm workspaces) and supermon doesn't like the dependencies that use other pnpm workspace packages:

```
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

However, it should work fine. Maybe it is because it says npm and not pnpm...
So, is there a way to specify the package manager to use in dependency syncronization?

**Comment by mikkotikkanen** [comment]
Yeh, I'd say that would be the reason

![image](https://user-images.githubusercontent.com/391263/112766629-3a34fd00-901b-11eb-8382-7312f4c85433.png)

The fix should be simple enough though as I don't use pnpm myself what would be the most bulletproof way to detect if someone is using it instead of npm, as I would prefer automated way to do it?

**Comment by mikkotikkanen** [comment]
There is now a branch (!feat/configurable-packagemanager") with `--pm` option that should let you change the package manager to pnpm (`--pm=pnpm`)

Do you think you could test that branch if it works for you?

Should be doable by pulling the branch in question, running `npm link` in the directory and then trying it out in your project

**Comment by mikkotikkanen** [comment]
@creepinson Can you confirm if the latest version now works with pnpm (with `--pmexec=pnpm` option
